### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by amaanam** [INFO-526-S24/project-final-GraphicalGeniuses#2]
The following is the peer review of the project proposal by Insight Architects. The team members that participated in this review are 

- Eeshaan Sourabh Reddy Mummila - @EeshaanReddy
- Anusha Nagaraja - @anusharaj1997
- Amaan Mohammed Yunus Salim Mulla- @amaanam
- Kaarthik Sai Patibandla  - @zeuszapper
- Shreemithra Naveen - @shreemithran
- Ayesha Khatun - @ayeshakhatunsujana

- Describe the goal of the project.
The project aims to visually showcase the goal-scoring, and performing brilliance of Cristiano Ronaldo and Lionel Messi through interactive maps and animations. By analyzing their goals across competitions and seasons, it offers insights into their playing styles, achievements, and geographic impact. 

- Describe the data used or collected.

The data used in the project comprises detailed records of football matches involving Cristiano Ronaldo and Lionel Messi, sourced from the Ronaldo and Messi datasets available on Kaggle. Each dataset includes information such as the season, competition, match details (date, venue, opponent), result, playing position, minute of event occurrence, and type of event (e.g., goal, assist). Additionally, the datasets provide insights into the context of each goal, including the presence or absence of assists. With over 1,300 entries combined, the data covers goals scored by Ronaldo and Messi across various competitions, seasons, and playing positions, offering a comprehensive view of their goal-scoring performances up until 2022.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

• The research question will be explored using descriptive analysis and interactive data visualization methods. In the first topic, a side-by-side animation will illustrate the geographical distribution of goals scored by Ronaldo and Messi over time, highlighting unique competitions and countries. The second topic involves developing an interactive map to compare the goals scored by Ronaldo and Messi in different countries, with a focus on regional variations. Descriptive statistics and interactive mapping techniques will enable the examination and comprehension of goal-scoring trends from 2005 to 2022.

- Is there anything that is unclear from the proposal?
•The Analysis part seems to be missing, with the given data and the questions, we are unable to find the insights of the project idea and the Analysis plan of the overall project. 
•The plots or the visualization technique that will used is not mentioned or descriptions about the same are not given.

- Provide constructive feedback on how the team might be able to improve their project.

•Opponent Strength: 
Incorporate a column indicating the strength of the opponent team based on factors such as FIFA ranking, league position, or historical performance. This could help contextualize the difficulty of scoring goals against different opponents.

•Visualization Complexity: 
The side-by-side animation approach may result in a visually cluttered or confusing presentation, especially when displaying data for multiple seasons. Simplifying the visualization or providing alternative views could improve clarity.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

•Visual Enhancements: Explore different visualization techniques such as heatmaps or choropleth maps to better visualize the distribution of goals scored in each country over time.

•Comparative Analysis: 
Incorporate visual elements that enable direct comparison between Ronaldo and Messi, such as side-by-side bar charts or line graphs displaying their respective goal counts over time.

- Provide constructive feedback on any issues with file and/or code organization.
•Analysis and the descriptions lack certain explanations to fully understand the proposal of the project.

- (Optional) Any further comments or feedback?
•Expecting Analysis and description of the visualization techniques.

**Comment by Bolajiadewal3** [comment]
_Is there anything that is unclear from the proposal?
•The Analysis part seems to be missing, with the given data and the questions, we are unable to find the insights of the project idea and the Analysis plan of the overall project.
•The plots or the visualization technique that will used is not mentioned or descriptions about the same are not given._

**We have added an analysis section to both topics and included which visualization techniques we will be employing with each**



_Provide constructive feedback on any issues with file and/or code organization.
•Analysis and the descriptions lack certain explanations to fully understand the proposal of the project._

**We have included more in depth explanations to allow for easier understanding of the proposal of the project - including the major packages we will include**


_(Optional) Any further comments or feedback?
•Expecting Analysis and description of the visualization technique_

**We have added analysis sections and descriptions of the visualization techniques we intend to use**

**Thank you for your feedback, we have made changes accordingly**
