### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by ArunKoundinya** [INFO-526-S24/project-final-GraphicalGeniuses#6]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members that participated in this review are 

-Sachin Pandurang Patil - @sachinpatil3115
-Valerie Okine - @valerie-okine
-Arun Kondinya Parasa - @ArunKoundinya
-Surajit Pal - @sura789
-Christian Ortmann - @christian-ortmann
-Peter Yeh - @Peter-Yeh-coder

- Content: Is the research question well designed and is the data being used relevant to the research question?

    The approach is well designed and relevant. 

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

    The interpretation of the visualisations in initial world plots are relevant. And summarised well with a final interactive map. However, we felt that the racing bar plot could have been adopted as a visualisation to showcase the same information.
    
    The second part of the visualisation ; we liked the interactive column plots as it allows the user to play with information and deduce more.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
   
   Creativity of first part of the visualisations are very good.
   Critical thought of the second part of the visualisations are simple and easy to comprehend.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
   
     Slides are well organized. In the second part of the visualizations we felt the column plot width could have been small to make it more aesthetic. 

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

    Team presented very well. It indicates the team knows that they were presenting and the lot of information they were able to summarise in quick time is commendable.

**Comment by ustusharkant** [comment]
Thanks for your valuable remarks.
