### ISSUE TITLE
Code peer review

### ISSUE THREAD

**Issue by zeuszapper** [INFO-526-S24/project-final-GraphicalGeniuses#7]
The following is the peer review of the project proposal by Insight Architects. The team members that participated in this review are

Kaarthik Sai Patibandla - @zeuszapper

Eeshaan Sourabh Reddy Mummila - @EeshaanReddy

Anusha Nagaraja - @anusharaj1997

Amaan Mohammed Yunus Salim Mulla- @amaanam

Shreemithra Naveen - @shreemithran

Ayesha Khatun - @ayeshakhatunsujana

---

#### 1. Purpose of Code
- [x] Clearly defined and understood
- [ ] Ambiguous or unclear

Feedback: The presentation had a clear introduction, approach, topic discussion, and conclusion.
---

#### 2. Code Quality

- [x] Code is clean, readable, and well-organized
- [ ] Adequate comments explaining complex or tricky code sections
- [x] Variables, methods, and classes have meaningful names
- [ ] Consistent code style (indentation, naming conventions, etc.)
**Feedback:** In interactive plot, explanations of what light and deeper colors mean are missing.
**Feedback:** Not directly applicable; however, the presentation could improve by clarifying graphical elements (akin to variable naming).
**Feedback:** Suggestion to use GIFs instead of videos could be seen as a call for consistent multimedia formatting.
---

#### 3. Documentation

- [x] Code documentation (e.g., comments) is sufficient
- [x] Readme or other documentation updated if necessary

**Feedback:** The presentation lacks sufficient explanations for color usage in interactive plots which can be considered a form of 'documentation' within visual presentations.

---

#### 4. Best Practices

- [x] No hardcoded values; constants used appropriately
- [x] Security and privacy concerns addressed (e.g., no sensitive data exposed)
- [ ] Code avoids repetition and promotes reusability
**Feedback**: Using more versatile plots instead of very similar comparison plots might hint at avoiding 'hardcoded' visual approaches.
**Feedback:** We suggest that plots are very similar and could benefit from diverse visualization strategies, promoting visual reusability and avoiding repetition.
---

#### 5. Additional Comments

- Please provide feedback, areas of improvement, or other observations.
**Feedback:** The presentation took too much time, suggesting a need for more concise and effective communication. Consider streamlining content and focusing on key points to maintain audience engagement.
---

#### 6. Recommendation

- [ ] Approved - ready to be merged
- [x] Approved with minor issues - can be addressed later
- [ ] Requires changes - provide feedback and request another review

**Feedback:** Given the need for clearer explanations in interactive plots, more versatile plot usage, and improved time management,  we are going to approve with minor issues, but these are very important to change
---

**Comment by ustusharkant** [comment]
⁠1. Purpose of Code
**Feedback**: In interactive plot, explanations of what light and deeper colors mean are missing.
  
  We've added the colors only to distinguish the different countries where Ronaldo & Messi have scored the goals, the colors don't have any quantitative values.
  
  3. Documentation
  **Feedback**: The presentation lacks sufficient explanations for color usage in interactive plots which can be considered a form of 'documentation' within visual presentations.
  
  Has already mentioned above in point 1.
