### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by ayeshakhatunsujana** [INFO-526-S24/project-final-GraphicalGeniuses#8]
The following is the peer review of the Presentation proposal by **InsightArchitect.** The team members that participated in this review are 

**Ayesha Khatun** - @ayeshakhatunsujana

**Eeshaan Sourabh Reddy Mummila** - @EeshaanReddy

**Anusha Nagaraja** - @anusharaj1997

**Amaan Mohammed Yunus Salim Mulla**- @amaanam

**Shreemithra Naveen** - @shreemithran

**Kaarthik Sai Patibandla** - @zeuszapper

- Content: Is the research question well designed and is the data being used relevant to the research question?

**Yes the content as well as data are well designed** 

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

**Animation can be represented as a gif file not as a video** 

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

**⁠Yes, pretty much** 

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

**1. ⁠Slides are organized
2. ⁠In interactive plot, what does mean light color and what does mean by deeper color are not mentioned 
3. ⁠The comparison plots are very similar, can be presented  using more versatile plots**

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

**1. Clear introduction, approach, topic idea and conclusion 
2. ⁠They took to much time for presentation**

**Comment by ustusharkant** [comment]
2. ⁠In interactive plot, what does mean light color and what does mean by deeper color are not mentioned
We've added the colors only to distinguish the different countries where Ronaldo & Messi have scored the goals, the colors don't have any quantitative values.

**Comment by ayeshakhatunsujana** [comment]
Thank you for the clarifications.
